"""Generate the closed runtime catalogue from verified native UI compilations."""
from pathlib import Path
import argparse,hashlib,json

def main():
    parser=argparse.ArgumentParser();parser.add_argument('--compiled',type=Path,required=True);parser.add_argument('--output',type=Path,required=True)
    parser.add_argument('--profiles',type=Path,required=True)
    args=parser.parse_args();root=args.compiled.resolve(strict=True);manifest=json.loads((root/'graphics-manifest.json').read_text())
    rows=sorted(manifest['records'],key=lambda r:r['request']);assert len(rows)==466 and len({r['request'] for r in rows})==466
    lines=['// Generated by tools/text_languages/graphics_catalog.py. Jarvis-HOOK.',
           '// Only examined source/output pairs are admitted; no proprietary pixels are embedded.',
           '#pragma once','#include <cstddef>','#include <cstdint>','#include <string_view>',
           'namespace FfxHooks::TextLanguage {',
           'struct GraphicProfile { std::string_view request,source,output; std::uint32_t bytes; };',
           'inline constexpr GraphicProfile GraphicProfiles[]={']
    for r in rows:
        payload=(root/r['path']).read_bytes();assert hashlib.sha256(payload).hexdigest()==r['target_sha256'] and len(payload)==r['source_size']==r['size']
        assert r['outside_changed_blocks']==0
        lines.append(' {'+','.join([json.dumps(r['request']),json.dumps(r['source_sha256']),json.dumps(r['target_sha256']),str(r['size'])+'u'])+'},')
    lines+=['};', 'inline const GraphicProfile* FindGraphicProfile(std::string_view request) noexcept {',
            ' std::size_t first=0,last=sizeof(GraphicProfiles)/sizeof(GraphicProfiles[0]);',
            ' while(first<last){const auto middle=first+(last-first)/2;const auto& row=GraphicProfiles[middle];',
            '  if(row.request<request)first=middle+1;else last=middle;}',
            ' return first<sizeof(GraphicProfiles)/sizeof(GraphicProfiles[0])&&GraphicProfiles[first].request==request?&GraphicProfiles[first]:nullptr;',
            '}', '} // namespace FfxHooks::TextLanguage','']
    args.output.write_text('\n'.join(lines))
    profiles=[dict(request=r['request'],source_sha256=r['source_sha256'],sha256=r['target_sha256'],size=r['size']) for r in rows]
    args.profiles.write_text(json.dumps(dict(entries=profiles),indent=2)+'\n')
    print(json.dumps(dict(entries=len(rows),bytes=args.output.stat().st_size,sha256=hashlib.sha256(args.output.read_bytes()).hexdigest())))

if __name__=='__main__':main()
