#pragma once
// Existing LabMusicRuntimeName catalog; no game audio payload.
#include <cstdint>
namespace FfxHooks::ArenaSoundtrack {
struct Entry { std::uint16_t id; const char* name; };
inline constexpr Entry kTracks[]={
    {10, "Unwavering Decision"},
    {11, "Leap In The Dark"},
    {12, "Enemy Attack"},
    {13, "The Summoning"},
    {14, "Macalania Forest"},
    {15, "Wandering Flame"},
    {16, "Battle Theme"},
    {17, "Phantoms"},
    {18, "Out Of The Frying Pan"},
    {19, "Mi'ihen Road"},
    {20, "Wanna Ride The Ciparph"},
    {21, "Brave Advancement"},
    {22, "Spira Unplugged"},
    {23, "The Trials"},
    {24, "The Blitzers"},
    {25, "The Deceased Laugh"},
    {26, "Seymour's Ambition"},
    {27, "Blitz Off"},
    {28, "Crisis"},
    {29, "Thunder Plain"},
    {30, "Rikku's Theme"},
    {31, "Underwater Ruins"},
    {32, "Braska's Daughter"},
    {33, "Permitted Passage"},
    {34, "Seymour's Theme"},
    {35, "Confrontation"},
    {36, "Guadosalam"},
    {37, "People Of The North Pole"},
    {38, "Brass De Chocobo"},
    {39, "Besaid"},
    {40, "Blazing Desert"},
    {41, "The Truth Revealed"},
    {42, "Seymour Battle"},
    {43, "Illusion"},
    {44, "Creep"},
    {45, "Twilight"},
    {46, "Inori Effect"},
    {48, "Prelude"},
    {49, "Otherworld"},
    {50, "Decisive Battle"},
    {51, "Jecht's Theme"},
    {128, "Sprouting"},
    {129, "The Splendid Performance"},
    {130, "Zanarkand"},
    {131, "Start"},
    {132, "Djose Temple"},
    {133, "Travel Company"},
    {134, "Yuna's Decision"},
    {135, "Path Of Repentance"},
    {136, "Yuna's Theme"},
    {137, "My Father's Murderer"},
    {138, "Victory Fanfare"},
    {139, "Silence Before The Storm"},
    {140, "Game Over"},
    {141, "Someday The Dream Will End"},
    {142, "Nostalgia"},
    {143, "Good Night"},
    {144, "Hum Of The Fayth"},
    {145, "A Challenge"},
    {146, "Auron's Theme"},
    {147, "Luca"},
    {148, "Wakka's Theme"},
    {149, "Hum Of The Fayth"},
    {150, "Song Of Prayer Bahamut"},
    {151, "Song Of Prayer Anima"},
    {152, "Song Of Prayer Ixion"},
    {153, "Song Of Prayer Bodyguard"},
    {154, "Song Of Prayer Ifrit"},
    {155, "Song Of Prayer Shiva"},
    {156, "Hymn Valefor"},
    {157, "Song Of Prayer Spira"},
    {158, "Song Of Prayer The Lonzo"},
    {159, "Song Of Prayer Yunalesca"},
    {160, "Hum Of The Fayth"},
    {161, "Tidus's Theme"},
    {162, "At The End Of The Abyss"},
    {163, "Oui Are Al Bhed"},
    {164, "The Advancers"},
    {165, "Run"},
    {166, "Raid"},
    {167, "Marriage Ceremony"},
    {168, "Tragedy"},
    {169, "I Can Fly"},
    {170, "Sea Of Mists"},
    {171, "Lulu's Theme"},
    {172, "Darkness"},
    {174, "Time Of Judgment"},
    {176, "Summoned Beasts Battle"},
    {177, "Reception For Great Sage Micah"},
    {178, "The Temple Band"},
    {179, "Song Of Prayer Spira"},
    {181, "Raid"},
};
inline const Entry* Get(std::uint16_t id) noexcept { for(const auto& t:kTracks)if(t.id==id)return &t;return nullptr; }
}
