#pragma once
#include "EquipmentWorkshopCatalogBridge.h"
namespace FfxHooks::EquipmentWorkshop::Names {
inline constexpr const char* abilities[]={
 "Sensor",
 "First Strike",
 "Initiative",
 "Counterattack",
 "Evade & Counter",
 "Magic Counter",
 "Magic Booster",
 "Alchemy",
 "Auto-Potion",
 "Auto-Med",
 "Auto-Phoenix",
 "Piercing",
 "Half MP Cost",
 "One MP Cost",
 "Double Overdrive",
 "Triple Overdrive",
 "SOS Overdrive",
 "Overdrive to AP",
 "Double AP",
 "Triple AP",
 "No AP",
 "Pickpocket",
 "Master Thief",
 "Break HP Limit",
 "Break MP Limit",
 "Break Damage Limit",
 "Gillionaire",
 "HP Stroll",
 "MP Stroll",
 "No Encounters",
 "Firestrike",
 "Fire Ward",
 "Fireproof",
 "Fire Eater",
 "Icestrike",
 "Ice Ward",
 "Iceproof",
 "Ice Eater",
 "Lightningstrike",
 "Lightning Ward",
 "Lightningproof",
 "Lightning Eater",
 "Waterstrike",
 "Water Ward",
 "Waterproof",
 "Water Eater",
 "Deathstrike",
 "Deathtouch",
 "Deathproof",
 "Death Ward",
 "Zombiestrike",
 "Zombietouch",
 "Zombieproof",
 "Zombie Ward",
 "Stonestrike",
 "Stonetouch",
 "Stoneproof",
 "Stone Ward",
 "Poisonstrike",
 "Poisontouch",
 "Poisonproof",
 "Poison Ward",
 "Sleepstrike",
 "Sleeptouch",
 "Sleepproof",
 "Sleep Ward",
 "Silencestrike",
 "Silencetouch",
 "Silenceproof",
 "Silence Ward",
 "Darkstrike",
 "Darktouch",
 "Darkproof",
 "Dark Ward",
 "Slowstrike",
 "Slowtouch",
 "Slowproof",
 "Slow Ward",
 "Confuseproof",
 "Confuse Ward",
 "Beserkproof",
 "Beserk Ward",
 "Curseproof",
 "Curse Ward",
 "Auto-Shell",
 "Auto-Protect",
 "Auto-Haste",
 "Auto-Regen",
 "Auto-Reflect",
 "SOS Shell",
 "SOS Protect",
 "SOS Haste",
 "SOS Regen",
 "SOS Reflect",
 "SOS NulTide",
 "SOS NulFrost",
 "SOS NulShock",
 "SOS NulBlaze",
 "Strength +3%",
 "Strength +5%",
 "Strength +10%",
 "Strength +20%",
 "Magic +3%",
 "Magic +5%",
 "Magic +10%",
 "Magic +20%",
 "Defense +3%",
 "Defense +5%",
 "Defense +10%",
 "Defense +20%",
 "Magic Def +3%",
 "Magic Def +5%",
 "Magic Def +10%",
 "Magic Def +20%",
 "HP +5%",
 "HP +10%",
 "HP +20%",
 "HP +30%",
 "MP +5%",
 "MP +10%",
 "MP +20%",
 "MP +30%",
 "Capture",
 "Aeon Immunities",
 "Distill Power",
 "Distill Mana",
 "Distill Speed",
 "Distill Ability",
 "Ribbon",
 "Double Drop",
 "Triple Drop",
};
// Item IDs/names from the existing project dictionary; Customize recipes are separate.
inline constexpr const char* items[]={
 "Potion",
 "Hi-Potion",
 "X-Potion",
 "Mega-Potion",
 "Ether",
 "Turbo Ether",
 "Phoenix Down",
 "Mega Phoneix",
 "Elixir",
 "Mega Elixir",
 "Antidote",
 "Soft",
 "Eye Drops",
 "Echo Screen",
 "Holy Water",
 "Remedy",
 "Power Distiller",
 "Mana Distiller",
 "Speed Distiller",
 "Ability Distiller",
 "Al Bhed Potion",
 "Healing Water",
 "Tetra Elemental",
 "Antartic Wind",
 "Artic Wind",
 "Ice Gem",
 "Bomb Fragment",
 "Bomb Core",
 "Fire Gem",
 "Electro Marble",
 "Lightning Marble",
 "Lightning Gem",
 "Fish Scale",
 "Dragon Scale",
 "Water Gem",
 "Grenade",
 "Frag Grenade",
 "Sleeping Powder",
 "Dream Powder",
 "Silence Grenade",
 "Smoke Bomb",
 "Shadow Gem",
 "Shining Gem",
 "Blessed Gem",
 "Supreme Gem",
 "Poison Fang",
 "Silver Hourglass",
 "Gold Hourglass",
 "Candle of Life",
 "Petrify Grenade",
 "Farplane Shadow",
 "Farplane Wind",
 "Designer Waller",
 "Dark Matter",
 "Chocobo Feather",
 "Chocobo Wing",
 "Lunar Curtain",
 "Light Curtain",
 "Star Curtain",
 "Healing Spring",
 "Mana Spring",
 "Stamina Spring",
 "Soul Spring",
 "Purifying Salt",
 "Stamina Tablet",
 "Mana Tablet",
 "Twin Stars",
 "Stamina Tonic",
 "Mana Tonic",
 "Three Stars",
 "Power Sphere",
 "Mana Sphere",
 "Speed Sphere",
 "Ability Sphere",
 "Fortune Sphere",
 "Attribute Sphere",
 "Special Sphere",
 "Skill Sphere",
 "Wht Magic Sphere",
 "Blk Magic Sphere",
 "Master Sphere",
 "Lv.1 Key Sphere",
 "Lv.2 Key Sphere",
 "Lv.3 Key Sphere",
 "Lv.4 Key Sphere",
 "HP Sphere",
 "MP Sphere",
 "Strength Sphere",
 "Defense Sphere",
 "Magic Sphere",
 "Magic Def Sphere",
 "Agility Sphere",
 "Evasion Sphere",
 "Accuracy Sphere",
 "Luck Sphere",
 "Clear Sphere",
 "Return Sphere",
 "Friend Sphere",
 "Teleport Sphere",
 "Warp Sphere",
 "Map",
 "Rename Card",
 "Musk",
 "Hypello Potion",
 "Shining Thorn",
 "Pendulum",
 "Amulet",
 "Door to Tomorrow",
 "Wings to Discovery",
 "Gambler's Spirit",
 "Underdog's Secret",
 "Winning Formula",
};
inline const char* Item(unsigned id){return id<112?items[id]:"Unknown material";}
inline const char* Ability(unsigned word){return word>=0x8000&&word<0x8083?abilities[word-0x8000]:word>=0x8087&&word<=0x8FFF?CatalogBridge::Name(word):"Empty";}
inline constexpr const char* owners[]={"Tidus","Yuna","Auron","Kimahri","Wakka","Lulu","Rikku"};
}
