#!/usr/bin/env python3
"""Generate bounded admission signatures from the one supported private executable.

Does not run or modify the executable. Small target signatures are emitted to the
requested C++ header; disassembly packets remain in a caller-selected private path.
"""
from __future__ import annotations
import argparse
import hashlib
import json
import re
from pathlib import Path
import pefile
import capstone
from capstone.x86 import X86_OP_IMM
from native_probe import EXPECTED_SHA256


def main() -> None:
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('executable',type=Path)
    parser.add_argument('--header',type=Path,required=True)
    parser.add_argument('--packet',type=Path,required=True)
    args=parser.parse_args()
    raw=args.executable.read_bytes()
    if hashlib.sha256(raw).hexdigest()!=EXPECTED_SHA256:
        parser.error('unsupported executable identity')
    pe=pefile.PE(data=raw)
    base=pe.OPTIONAL_HEADER.ImageBase
    if base!=0x400000 or pe.FILE_HEADER.Machine!=0x14c:
        parser.error('unsupported native profile')
    md=capstone.Cs(capstone.CS_ARCH_X86,capstone.CS_MODE_32);md.detail=True
    constants=Path('src/runtime/FfxHooksDll/shared/ffx_addresses.h').read_text(encoding='utf-8')
    def constant(name: str) -> int:
        found=re.search(r'^#define\s+'+re.escape(name)+r'\s+(0x[0-9a-fA-F]+)',constants,re.M)
        if not found: raise ValueError('missing exact constant '+name)
        return int(found.group(1),16)
    specs={
        'WardWriteback':(0x38edd9,8), 'WardFrame':(0x38e680,9),
        'WardLoop':(0x38edc1,10), 'WardAftermath':(0x38f0b0,48),
        'WardHitLoop':(0x389800,48), 'WardActor':(0x394030,64),
        'GridGrant':(0x385d10,48), 'GridBuildMenu':(0x39bb70,48),
        'GridHasCommand':(0x39ad40,48), 'GridCommandEntry':(0x390ae0,48),
        'GridPrepare':(constant('RVA_FFX_BTL_PREPARE_SAVE_COMMAND_STATE'),48),
        'LoadCallA':(0x4b2aea,5), 'LoadCallB':(0x4b3080,5), 'LoadCallC':(0x4b4e97,5),
        'GridLoad':(0x645570,48), 'GridRenderConstructor':(0x281db0,48),
        'PhotoPosition':(0x42b500,48), 'PhotoUpdate':(0x432e90,48),
    }
    relocs=[e.rva for b in pe.DIRECTORY_ENTRY_BASERELOC for e in b.entries if e.type==3]
    proofs=[]
    for name,(rva,length) in specs.items():
        code=pe.get_data(rva,length)
        if len(code)!=length: raise ValueError('short source '+name)
        offsets=[v-rva for v in relocs if rva<=v and v+4<=rva+length]
        if any(v<rva+length and v+4>rva and v-rva not in offsets for v in relocs):
            raise ValueError('signature splits a relocation: '+name)
        proofs.append((name,rva,code,offsets))
    # These are measured instruction sites, never a runtime memory scan. Every
    # selected instruction must still match its complete bytes before installation.
    menu_sites=[]
    for ins in md.disasm(pe.get_data(0x39bb70,0x500),base+0x39bb70):
        if ins.mnemonic=='cmp' and any(o.type==X86_OP_IMM and o.imm==320 for o in ins.operands):
            if ins.imm_size!=4 or len(ins.bytes)<5:
                raise ValueError('unsupported menu comparison encoding')
            menu_sites.append({'rva':ins.address-base,'bytes':ins.bytes.hex(),
                               'immediate_offset':ins.imm_offset,'length':ins.size})
    if not 1<=len(menu_sites)<=8: raise ValueError('unexpected menu limit site count')
    lines=['#pragma once','#include <cstddef>','#include <cstdint>',
           '// Generated by tools/recovery/build_evidence.py; exact SHA-256 '+EXPECTED_SHA256,
           'namespace FfxHooks::RecoveryEvidence {',
           'struct Proof {std::uint32_t rva; const std::uint8_t* bytes; std::size_t size; const std::uint16_t* relocations; std::size_t relocationCount;};']
    for name,rva,code,offsets in proofs:
        lines.append('inline constexpr std::uint8_t '+name+'Bytes[]={'+','.join('0x%02x'%b for b in code)+'};')
        lines.append('inline constexpr std::uint16_t '+name+'Relocs[]={'+(','.join(map(str,offsets)) or '0')+'};')
        lines.append('inline constexpr Proof '+name+'={0x%x,%sBytes,sizeof(%sBytes),%sRelocs,%d};'%(rva,name,name,name,len(offsets)))
    lines.append('struct MenuLimit {std::uint32_t rva; std::uint8_t bytes[6]; std::uint8_t size,immediate;};')
    lines.append('inline constexpr MenuLimit menuLimits[]={')
    for site in menu_sites:
        values=bytes.fromhex(site['bytes'])
        lines.append('{0x%x,{%s},%d,%d},'%(site['rva'],','.join('0x%02x'%b for b in values),len(values),site['immediate_offset']))
    lines+=['};','} // namespace FfxHooks::RecoveryEvidence','']
    args.header.parent.mkdir(parents=True,exist_ok=True)
    args.header.write_text('\n'.join(lines),encoding='utf-8')
    packet={'executable_sha256':EXPECTED_SHA256,'menu_limits':menu_sites,'slices':{}}
    slices={'grid_constructor':(0x6823c7,0x302),'grid_build_nodes':(0xa51340,0x230),
            'grid_reserved_draw':(0xa5a450,0x110),'grid_activate':(0xa48910,0x400),
            'grid_enter':(0xa54860,0x400),'grid_exit':(0xa54660,0x200),
            'grid_update_node':(0xa45930,0x450),'grid_animation':(0xa58080,0x280),
            'upload':(0x712330,0x280),'load_copy':(0x8b5450,0x20),
            'load_caller_a':(0x8b2ada,0x25),'load_caller_b':(0x8b3070,0x25),
            'load_caller_c':(0x8b4e70,0x32)}
    for name,(va,size) in slices.items():
        code=pe.get_data(va-base,size)
        packet['slices'][name]={'va':hex(va),'size':size,'sha256':hashlib.sha256(code).hexdigest(),
             'instructions':['%08X %-24s %s %s'%(i.address,i.bytes.hex(),i.mnemonic,i.op_str) for i in md.disasm(code,va)]}
    args.packet.parent.mkdir(parents=True,exist_ok=True)
    args.packet.write_text(json.dumps(packet,indent=2),encoding='utf-8')
    print(json.dumps({'header':str(args.header),'proofs':len(proofs),'menu_limits':menu_sites,'packet':str(args.packet)},indent=2))

if __name__=='__main__':
    main()
