"""Generate reviewed RNG code witnesses from the user's two exact private PEs."""
from pathlib import Path
import argparse,hashlib,json,re,struct
import pefile
ROOT=Path(__file__).resolve().parents[2]
SITES={
 'Initializer':(0x3988a0,0x398890,85), 'Clock':(0x398960,0x398950,69),
 'Normal':(0x3989b0,0x3989a0,39), 'Indexed':(0x398900,0x3988f0,55),
 'Reset':(0x487da0,0x487e30,80), 'CounterGetter':(0x487d80,0x487e10,8),
 'InitCaller':(0x386ed5,0x386e15,5), 'ResetCaller':(0x48e4fe,0x48e58e,5),
}
DATA={
 'NormalState':(0x8421f0,0x842200),'AuxiliaryState':(0x8421f4,0x842204),
 'Channels':(0xd35ed8,0xd35ee0),'Multipliers':(0x8421f8,0x842208),
 'Xors':(0x842308,0x842318),'Counter':(0xf301d0,0xf30210),
}
HASHES=['78ce34397da5e6f49b72c2aebadedaf4cd3f6720e1949d46a1b8ed67d3db5ced','0537b2a1047f3266e73495cd4e35f63f0777f4231d417699f979954686da686d']
def generate(paths):
 images=[];records=[]
 for index,path in enumerate(paths):
  blob=path.read_bytes();assert hashlib.sha256(blob).hexdigest()==HASHES[index]
  pe=pefile.PE(data=blob);assert pe.OPTIONAL_HEADER.ImageBase==0x400000 and pe.FILE_HEADER.Machine==0x14c
  relocs={e.rva for b in pe.DIRECTORY_ENTRY_BASERELOC for e in b.entries if e.type==3}
  images.append((pe,relocs))
  for call,target in [('InitCaller','Initializer'),('ResetCaller','Reset')]:
   rva=SITES[call][index];data=pe.get_data(rva,5)
   assert data[0]==0xe8 and rva+5+struct.unpack_from('<i',data,1)[0]==SITES[target][index],call
 lines=['// Jarvis-HOOK: exact private PE witnesses; generated by tools/rng/generate_original_ps2_evidence.py.','#pragma once','#include "RecoveryEvidence.generated.h"','namespace FfxHooks::OriginalPs2Rng::Evidence {']
 for name,(legacy,current,size) in SITES.items():
  lines.append(f'inline constexpr std::uint32_t {name}Rva=ExecutableProfile::Rva<0x{legacy:08X}u>();')
  for i,(pe,relocs) in enumerate(images):
   rva=(legacy,current)[i];data=pe.get_data(rva,size);assert len(data)==size
   offsets=sorted(x-rva for x in relocs if rva<=x<rva+size);assert all(x+4<=size for x in offsets)
   lines.append('#ifndef FFXHOOKS_TARGET_STEAM_20261001' if i==0 else '#else')
   lines.append(f'inline constexpr std::uint8_t {name}Bytes[]={{'+','.join(f'0x{x:02X}' for x in data)+'};')
   if offsets:lines.append(f'inline constexpr std::uint16_t {name}Relocations[]={{'+','.join(str(x) for x in offsets)+'};')
   lines.append(f'inline constexpr RecoveryEvidence::Proof {name}={{{name}Rva,{name}Bytes,sizeof({name}Bytes),'+(name+'Relocations' if offsets else 'nullptr')+f',{len(offsets)}'+'};')
   records.append({'name':name,'profile':i,'rva':rva,'bytes':data.hex(),'relocations':offsets})
  lines.append('#endif')
 for name,(legacy,current) in DATA.items():lines.append(f'inline constexpr std::uint32_t {name}Rva=ExecutableProfile::Rva<0x{legacy:08X}u>();')
 for name,size in [('Multipliers',272),('Xors',136)]:
  blobs=[p.get_data(DATA[name][i],size) for i,(p,_) in enumerate(images)];assert blobs[0]==blobs[1]
  lines.append(f'inline constexpr std::uint8_t {name}Bytes[]={{'+','.join(f'0x{x:02X}' for x in blobs[0])+'};')
 lines.append('} // namespace FfxHooks::OriginalPs2Rng::Evidence')
 return '\n'.join(lines)+'\n',records
if __name__=='__main__':
 p=argparse.ArgumentParser(description=__doc__);p.add_argument('--legacy',type=Path,required=True);p.add_argument('--steam',type=Path,required=True);p.add_argument('--output',type=Path,required=True);p.add_argument('--receipt',type=Path,required=True);a=p.parse_args()
 text,records=generate([a.legacy,a.steam]);a.output.write_text(text);a.receipt.write_text(json.dumps({'producer':'Jarvis-HOOK','hashes':HASHES,'witnesses':records,'data':DATA},indent=2)+'\n')
 print('Generated',len(SITES),'code/caller witnesses per profile and identical native channel tables')
