#!/usr/bin/env python3
"""Validate and compile authored DLL UI catalogs. Jarvis-HOOK; no network input."""
from __future__ import annotations
import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "locales/ui"
OUTPUT = ROOT / "src/runtime/FfxHooksDll/hooks/UiLanguageCatalog.inl"
LOCALES = ("en", "pt", "es", "fr", "it", "de", "ja", "ko", "zh")
# Whitespace after a percent is prose (e.g. '25% of damage'), never a UI format.
FORMAT = re.compile(r"%(?:[-+#0]*(?:[0-9]+|\*)?(?:\.(?:[0-9]+|\*))?(?:hh|ll|I64|[hlzjtL])?[diuoxXfFeEgGaAcspn]|%)")
FORMAT_WITH_SPACE = re.compile(FORMAT.pattern.replace("[-+#0]", "[-+#0 ]"))

def native_flag_strings() -> set[str]:
    """Read native identities; the Windows harness also checks F8FlagAt()."""
    hooks = ROOT / "src/runtime/FfxHooksDll/hooks"
    source = (hooks / "F8FlagCatalog.cpp").read_text(encoding="utf-8-sig")
    body = source.split("const F8FlagSpec kFlags[] = {", 1)[1].split("\n};", 1)[0]
    literal = r'"(?:\\.|[^"\\])*"'
    required = {json.loads(value) for value in re.findall(
        r'\{\s*"(?:System|Boosters|Cheats|Extras|Input|Dev|Reforge)"\s*,\s*(' + literal + ')', body)}
    required.update(json.loads(value) for value in re.findall(literal, body)
                    if re.match(r'"(?:LIVE|RESTART REQUIRED|READ ONLY|NOT WIRED) - .+', value)
                    and not value.endswith(' - "'))
    vanguard = (hooks / "VanguardCatalog.h").read_text(encoding="utf-8-sig")
    required.update(json.loads(value) for value in re.findall(
        r'\{\s*' + literal + r'\s*,\s*(' + literal + r')\s*,\s*Group::', vanguard))
    required.update("RESTART REQUIRED - " + json.loads(value) for value in re.findall(
        r'VANGUARD_GATE\(\d+,\s*' + literal + r',\s*(' + literal + r')\)', body))
    mods = (hooks / "ModFeatureCatalog.h").read_text(encoding="utf-8-sig")
    required.update(json.loads(value) for value in re.findall(r'\{\s*(' + literal + r')\s*,\s*\{', mods))
    required.update(json.loads(value) for value in re.findall(literal, mods)
                    if value.startswith('"RESTART REQUIRED - '))
    return required


def load_rows(source: Path = SOURCE) -> list[list[str]]:
    rows: dict[str, list[str]] = {}
    for path in sorted(source.glob("*.tsv")):
        for number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
            if not line or line.startswith("#"):
                continue
            values = line.split("\t")
            location = f"{path.name}:{number}"
            if len(values) != len(LOCALES) or any(not value for value in values):
                raise ValueError(f"{location}: expected nine nonempty locale values")
            if values[0] in rows:
                raise ValueError(f"{location}: duplicate source {values[0]!r}")
            expected = FORMAT.findall(values[0])
            if any(token.endswith("n") for token in FORMAT_WITH_SPACE.findall(values[0])):
                raise ValueError(f"{location}: forbidden write-through format")
            for locale, value in zip(LOCALES, values):
                value.encode("utf-8", errors="strict")
                if any(token.endswith("n") for token in FORMAT_WITH_SPACE.findall(value)):
                    raise ValueError(f"{location}: forbidden write-through format in {locale}")
                if any(ord(char) < 32 for char in value) or len(value.encode("utf-8")) >= 2048:
                    raise ValueError(f"{location}: invalid control/length in {locale}")
                if FORMAT.findall(value) != expected:
                    raise ValueError(f"{location}: {locale} format arguments differ")
            rows[values[0]] = values
    if not rows:
        raise ValueError("No UI catalog rows found")
    return [rows[key] for key in sorted(rows, key=lambda key: key.encode("utf-8"))]

def generate(rows: list[list[str]]) -> str:
    lines = ["// Generated by tools/ui_languages/catalog.py; edit locales/ui/*.tsv.",
             "inline constexpr Entry Catalog[] = {"]
    for row in rows:
        # ASCII C++ source keeps every compiler independent of its local codepage.
        # JSON surrogate pairs are not valid C++ universal character names.
        # Emit one C++ scalar escape for supplementary Unicode characters.
        literals = ["".join(char if ord(char) < 128 else
                            (f"\\u{ord(char):04x}" if ord(char) <= 0xffff else f"\\U{ord(char):08x}")
                            for char in json.dumps(value, ensure_ascii=False)) for value in row]
        lines.append("    {{" + ",".join("u8" + literal for literal in literals) + "}},")
    return "\n".join(lines + ["};", ""])

def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    try:
        rows = load_rows()
        generated = generate(rows)
        if args.check:
            if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != generated:
                raise ValueError("Generated UI catalog is absent or stale; run catalog.py")
        else:
            OUTPUT.write_text(generated, encoding="utf-8", newline="\n")
        print(f"UI catalog: {len(rows)} rows x {len(LOCALES)} locales; UTF-8 and format parity passed")
        return 0
    except (ValueError, UnicodeError, OSError) as error:
        print(f"UI catalog error: {error}")
        return 1

if __name__ == "__main__":
    raise SystemExit(main())
