#!/usr/bin/env python3
"""Generate ingredient facts from an explicitly supplied private kaizou.bin.

The binary is input-only and is never added to the repository. Missing recipes
are explicit mod-only entries, not alleged vanilla Customize recipes.
"""
from __future__ import annotations
import argparse
import hashlib
from pathlib import Path
import struct

MISSING_NATIVE = {20, 83, 122, 123, 129, 130}

def parse(data: bytes) -> dict[int, tuple[int, int, int]]:
    if len(data) < 20 or struct.unpack_from('<I', data)[0] != 1:
        raise ValueError('Unsupported customization header')
    last, stride, length, offset = struct.unpack_from('<HHHI', data, 10)
    if stride != 8 or offset != 20 or length != (last + 1) * stride or len(data) != offset + length:
        raise ValueError('Invalid customization bounds')
    rows: dict[int, tuple[int, int, int]] = {}
    for kind, word, item, quantity in struct.iter_unpack('<4H', data[offset:]):
        if kind not in (1, 2) or not 0x8000 <= word <= 0x8082 or not 0x2000 <= item < 0x2070 or not 1 <= quantity <= 255:
            raise ValueError('Invalid customization recipe')
        ability = word - 0x8000
        if ability in rows:
            raise ValueError('Duplicate customization ability')
        rows[ability] = item - 0x2000, quantity, kind
    if set(range(131)) - rows.keys() != MISSING_NATIVE:
        raise ValueError('Customization coverage differs; review the mod-only recipe list')
    return rows

def render(data: bytes) -> str:
    rows = parse(data)
    lines = ['#pragma once', '// Generated by tools/generate_customize_recipes.py from the private game table.',
             '// Zero quantity means no native recipe; the economy applies its explicit mod fallback.',
             'namespace workshop {', 'struct CustomizeRecipe { unsigned short item, quantity; unsigned char kind; };',
             f'inline constexpr const char* CustomizeSourceSha256="{hashlib.sha256(data).hexdigest()}";',
             'inline constexpr CustomizeRecipe CustomizeRecipes[131]={']
    for ability in range(131):
        item, qty, kind = rows.get(ability, (73, 0, 3))
        lines.append(f'    {{{item},{qty},{kind}}}, // {ability}' + (' - MOD ONLY (no native recipe)' if not qty else ''))
    lines.extend(['};', '}',''])
    return '\n'.join(lines)

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('kaizou', type=Path)
    parser.add_argument('--output', type=Path, default=Path(__file__).resolve().parents[1]/'include/customize_recipes.h')
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    data = args.kaizou.read_bytes()
    content = render(data)
    if args.check:
        if args.output.read_text(encoding='utf-8') != content:
            raise SystemExit('Customization recipe header differs from the supplied game table')
    else:
        args.output.write_text(content, encoding='utf-8')
    print('CUSTOMIZE_RECIPES_OK native=125 mod_only=6 sha256='+hashlib.sha256(data).hexdigest())
