#!/usr/bin/env python3
"""Generate/check the manually classified 97-item mod backlog traceability ledger."""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
BACKLOG = ROOT / "docs" / "MOD_IDEAS_BACKLOG.md"
LEDGER = Path(__file__).with_name("feature_ledger.tsv")
BACKLOG_SHA256 = "241a87e5fe3dbc3c414ca4024134cdcd9171c35abbe285cd3edcb07bb3f24ef4"

# Each line follows the order of its MOD's unchecked boxes in the frozen backlog.
# route | evidence | confidence | verdict | next gate
MAP = {
    "MOD-001": """
DATA_HOOK|HOOKS_KIM+EDITOR_CMD|MEDIUM|SOURCE_ONLY|DEFINE_RULE
DATA_HOOK|MONMAGIC|MEDIUM|RT0_PASS|DEFINE_MONSTERS
HOOK|PE11|MEDIUM|NEEDS_SPEC|DEFINE_CONDITION
HOOK|PE11+MODEL_CPP|HIGH|MODEL_PASS|DEFINE_CAP
DATA|AEON7|HIGH|RT0_PASS|RT2_FINITE
DATA|AEON7|HIGH|RT0_PASS|RT2_FINITE
DECISION|FORUM|LOW|NEEDS_SPEC|DEFINE_SCOPE
RESEARCH|LEDGER|HIGH|STATIC_PASS|ASTRA_REVIEW
RESEARCH|EDITOR_CMD+PE11|MEDIUM|SOURCE_ONLY|RT2_FINITE
DECISION|HOOKS_KIM|LOW|NEEDS_SPEC|DEFINE_RULE
DECISION|FORUM|LOW|NEEDS_SPEC|DEFINE_MONSTERS
DECISION|FORUM|LOW|NEEDS_SPEC|DEFINE_CAP
DATA|AEON7|HIGH|RT0_PASS|RT2_FINITE
""",
    "MOD-002": """
HOOK|PE11+MODEL_CPP|HIGH|MODEL_PASS|DEFINE_CAP
DATA_HOOK|EDITOR_GEAR+LUNA_IDA|MEDIUM|SOURCE_ONLY|MAP_EFFECT
HOOK|MODEL_CPP|MEDIUM|MODEL_PARTIAL|DEFINE_FORMULA
HOOK|PE11+LUNA_IDA|MEDIUM|SOURCE_ONLY|MAP_EFFECT
HOOK|PE11+LUNA_IDA|MEDIUM|SOURCE_ONLY|MAP_CTB
HOOK|MODEL_CPP|HIGH|MODEL_PASS|RT2_FINITE
HOOK|MODEL_CPP|HIGH|MODEL_PASS|RT2_FINITE
HOOK|PE11+EDITOR_CMD|HIGH|SOURCE_ONLY|FORMULA_ID
HOOK|LUNA_IDA|MEDIUM|SOURCE_ONLY|MAP_TURN_END
HOOK|PE11+MODEL_CPP|MEDIUM|MODEL_PARTIAL|DEFINE_ELEMENT_PAIR
HOOK|LUNA_IDA+MODEL_CPP|MEDIUM|MODEL_PASS|MAP_STATUS
DATA_HOOK|EDITOR_CMD+MODEL_CPP|MEDIUM|MODEL_PARTIAL|DEFINE_RANK
HOOK|LUNA_IDA|MEDIUM|SOURCE_ONLY|DEFINE_STATUS
DATA_HOOK|MODEL_CPP|MEDIUM|MODEL_PARTIAL|MAP_DURATION_FIELD
HOOK|LUNA_IDA|MEDIUM|SOURCE_ONLY|MAP_THREATEN
HOOK|PE11|MEDIUM|SOURCE_ONLY|DEFINE_ACCURACY
RESEARCH|FORUM|LOW|NEEDS_SPEC|IDENTIFY_ATTACKS
DATA_HOOK|EDITOR_CMD|LOW|NEEDS_RE|MAP_STAT_CAPS
HOOK|PE11+EDITOR_CMD|MEDIUM|SOURCE_ONLY|DEFINE_FORMULA
HOOK|FORUM+MODEL_CPP|HIGH|CORRECTED|MAP_MAGIC_FORMULA
DATA_HOOK|PE11+MODEL_CPP|MEDIUM|MODEL_PARTIAL|RT2_FINITE
HOOK|FORUM|LOW|NEEDS_RE|MAP_SWITCH_CTB
HOOK|MODEL_CPP|MEDIUM|MODEL_PARTIAL|RT2_FINITE
HOOK|MODEL_CPP|MEDIUM|MODEL_PARTIAL|MAP_AP_AWARD
DATA_HOOK|FORUM+MODEL_CPP|MEDIUM|MODEL_PARTIAL|DEFINE_CRIT
DATA_HOOK|FORUM+MODEL_CPP|HIGH|CORRECTED|DEFINE_ELEMENT_BOOST
DATA_HOOK|MODEL_CPP|MEDIUM|MODEL_PARTIAL|DEFINE_STACKING
DATA_HOOK|FORUM+MODEL_CPP|MEDIUM|MODEL_PARTIAL|DEFINE_COST_ROUNDING
DATA_HOOK|FORUM+MODEL_CPP|MEDIUM|MODEL_PARTIAL|MAP_KILL_EVENT
HOOK|FORUM|LOW|NEEDS_RE|MAP_COUNTER_EVENT
DATA_HOOK|FORUM+MODEL_CPP|MEDIUM|MODEL_PARTIAL|DEFINE_DAMAGE_TYPES
DECISION|FORUM|LOW|NEEDS_SPEC|DEFINE_CRIT
DATA_HOOK|FORUM+MODEL_CPP|MEDIUM|MODEL_PARTIAL|MAP_TURN_START
DATA_HOOK|FORUM+MODEL_CPP|MEDIUM|MODEL_PARTIAL|MAP_GUARD_EVA
DATA_HOOK|MODEL_CPP|MEDIUM|MODEL_PARTIAL|DEFINE_STACKING
DATA_HOOK|MODEL_CPP|MEDIUM|MODEL_PARTIAL|DEFINE_STACKING
DATA_HOOK|EDITOR_CMD+EDITOR_GEAR|LOW|NEEDS_RE|MAP_EQUIP_MENU
UI_HOOK|PE11+MODEL_CPP|MEDIUM|MODEL_PARTIAL|MAP_OD_UI
DECISION|FORUM|LOW|NEEDS_SPEC|DEFINE_PACKAGE
DECISION|FORUM|HIGH|STATIC_PASS|NO_ACTION
DECISION|PE11+EDITOR_CMD|MEDIUM|NEEDS_SPEC|FORMULA_ID
DECISION|FORUM|LOW|NEEDS_SPEC|DEFINE_PACKAGE
DECISION|FORUM|LOW|NEEDS_SPEC|DEFINE_STACKING
RESEARCH|FORUM|LOW|NEEDS_SPEC|CONFIRM_CTB_TEXT
DATA_HOOK|AEON_BREAK_RECIPE+AEON_WORKSHOP+AEON_CAP_PE+AA_EXPANSION|MEDIUM|RT0_PASS|AEON_HP_CAP_RT1
DATA_HOOK|AEON_BREAK_RECIPE+AEON_WORKSHOP+AEON_CAP_PE+AA_EXPANSION|MEDIUM|RT0_PASS|AEON_DAMAGE_CAP_RT1
DATA_HOOK|SPIRA_AA_SNAPSHOT+AA_EXPANSION|MEDIUM|RT0_PASS|SPIRA_EFFECTS_AND_OWNER_RT1
""",
    "MOD-003": """
HOOK|FANTASIA+PE11+MODEL_CPP|HIGH|MODEL_PASS|RT2_FINITE
DATA_HOOK|PLY_SAVE+EDITOR_CMD+HOOKS_KIM|MEDIUM|SOURCE_ONLY|MAP_NEW_GAME
DECISION|EDITOR_MIX|MEDIUM|NEEDS_SPEC|DEFINE_MIX
ASSET_GATE|FORUM|LOW|NEEDS_RE|ASSET_COMPATIBILITY
DATA_HOOK|EDITOR_CMD|LOW|NEEDS_RE|MAP_DOUBLECAST
ATEL_OR_HOOK|ATEL_REF|MEDIUM|SOURCE_ONLY|MAP_BOSS_SCRIPTS
DATA_HOOK|EDITOR_CMD|LOW|NEEDS_SPEC|IDENTIFY_ITEMS
ATEL_OR_HOOK|FORUM|LOW|NEEDS_RE|MAP_LIGHTNING_EVENT
DATA_HOOK|MODEL_CPP|MEDIUM|MODEL_PARTIAL|DEFINE_RANK
HOOK|MODEL_CPP|MEDIUM|MODEL_PARTIAL|DEFINE_FURY
DATA_HOOK|EDITOR_CMD+PE11|MEDIUM|SOURCE_ONLY|MAP_SUMMON_MENU
HOOK|LUNA_IDA|LOW|NEEDS_SPEC|DEFINE_STATUS
HOOK|LUNA_IDA|LOW|NEEDS_SPEC|DEFINE_KO
DATA_HOOK|PE11|LOW|NEEDS_RE|MAP_ABSORB_EVENT
UI_HOOK|FORUM|LOW|NEEDS_RE|MAP_BATTLE_HUD
UI_HOOK|LUNA_IDA|MEDIUM|SOURCE_ONLY|MAP_BATTLE_HUD
UI_HOOK|FORUM|LOW|NEEDS_RE|MAP_SUMMON_HUD
UI_HOOK|SAVE_CODE|LOW|NEEDS_RE|MAP_ARENA_FLAGS
DATA_HOOK|EDITOR_CMD|LOW|NEEDS_RE|MAP_SPHERE_MONITOR
DECISION|FORUM|LOW|NEEDS_SPEC|DEFINE_INSTANT
UI_HOOK|FORUM|LOW|NEEDS_RE|MAP_CTB_PREVIEW
ATEL_OR_HOOK|FORUM|LOW|NEEDS_RE|MAP_BUTTERFLY_FLAGS
HOOK|SAVE_CODE|LOW|NEEDS_RE|MAP_BATTLE_SAVE
HOOK|SAVE4|LOW|BLOCKED_SAVE|FIX_SAVE_LAYOUT
DATA_HOOK|EDITOR_CMD|LOW|NEEDS_RE|MAP_SPHERE_MONITOR
DATA|EDITOR_TEXT|MEDIUM|SOURCE_ONLY|TEXT_RT0
""",
    "MOD-004": """
DATA_HOOK|EDITOR_GEAR+SAVE4+MODEL_CPP|HIGH|BLOCKED_SAVE|FIX_SAVE_LAYOUT
DATA_HOOK|EDITOR_GEAR+SAVE4+MODEL_CPP|HIGH|BLOCKED_SAVE|FIX_SAVE_LAYOUT
DATA_HOOK|EDITOR_GEAR+SAVE4+MODEL_CPP|HIGH|BLOCKED_SAVE|DEFINE_SLOT_COST
DATA_HOOK|SAVE4+MODEL_CPP|HIGH|BLOCKED_SAVE|FIX_SAVE_LAYOUT
HOOK|MODEL_REFINEMENT+IDA_CUSTOMIZE+SAVE_FIXTURE|HIGH|MODEL_PARTIAL|REFINEMENT_EFFECTS_RT1
DATA_HOOK|MODEL_CPP+SAVE4|MEDIUM|BLOCKED_SAVE|DEFINE_EVOLUTION
""",
    "MOD-005": """
HOOK|PE_MOD005+SAVE_FIXTURE+EDITOR_GEAR|HIGH|NEEDS_RE|SIDECAR_RT1
""",
    "MOD-006": """
HOOK|LOCALE_RE+ENCODING_CORPUS+EDITOR_LOCALE|MEDIUM|NEEDS_RE|MAP_LANGUAGE_MENU_AND_RESOURCES
""",
    "MOD-007": """
DATA_HOOK|PE_MOD007+ELEMENT_SOURCE+MODEL_ELEMENTS|MEDIUM|MODEL_PARTIAL|ELEMENT_PIPELINE_RT1
""",
    "TEMPLATE": """
TEMPLATE|BACKLOG|HIGH|META|NO_ACTION
TEMPLATE|BACKLOG|HIGH|META|NO_ACTION
""",
}

ROUTES = {
    "DATA", "HOOK", "DATA_HOOK", "ATEL_OR_HOOK", "UI_HOOK",
    "ASSET_GATE", "DECISION", "RESEARCH", "TEMPLATE",
}
VERDICTS = {
    "RT0_PASS", "MODEL_PASS", "MODEL_PARTIAL", "SOURCE_ONLY",
    "NEEDS_SPEC", "NEEDS_RE", "BLOCKED_SAVE", "STATIC_PASS",
    "CORRECTED", "META",
}


def build() -> str:
    raw = BACKLOG.read_bytes()
    sha = hashlib.sha256(raw).hexdigest()
    if sha != BACKLOG_SHA256:
        raise ValueError(f"Backlog snapshot changed: {sha}")
    source = raw.decode("utf-8").split("## Jarvis-HOOK", 1)[0].splitlines()
    rows = ["id\tmod\tsource_line\troute\tevidence\tconfidence\tverdict\tnext_gate\tlabel"]
    counts: dict[str, int] = {}
    current: str | None = None
    for line_number, line in enumerate(source, 1):
        if line.startswith("## MOD-"):
            current = line[3:10]
            counts[current] = 0
        elif line.startswith("## Modelo para novas ideias"):
            current = "TEMPLATE"
            counts[current] = 0
        if not line.startswith("- [ ]"):
            continue
        if current not in MAP:
            raise ValueError(f"Checkbox outside known MOD at line {line_number}")
        ordinal = counts[current]
        values = MAP[current].strip().splitlines()
        if ordinal >= len(values):
            raise ValueError(f"Missing classification for {current} item {ordinal + 1}")
        route, evidence, confidence, verdict, gate = values[ordinal].strip().split("|")
        if route not in ROUTES or verdict not in VERDICTS or confidence not in {"HIGH", "MEDIUM", "LOW"}:
            raise ValueError(f"Invalid classification at {current} item {ordinal + 1}")
        counts[current] += 1
        item_id = f"{current}-{counts[current]:02d}"
        label = line[6:].replace("\t", " ").strip() or "(template checkbox)"
        rows.append(
            "\t".join((item_id, current, str(line_number), route, evidence,
                        confidence, verdict, gate, label))
        )
    for mod, values in MAP.items():
        if counts.get(mod, 0) != len(values.strip().splitlines()):
            raise ValueError(f"{mod}: classified {len(values.strip().splitlines())}, found {counts.get(mod)}")
    if sum(counts.values()) != 97:
        raise ValueError(f"Expected 97 checkboxes; found {sum(counts.values())}")
    return "\n".join(rows) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = build()
    if args.write:
        LEDGER.write_text(expected)
        print(f"WROTE {LEDGER}: 97 checkbox records (including 2 template rows)")
        return 0
    if not LEDGER.exists() or LEDGER.read_text() != expected:
        print("FAIL ledger differs from frozen backlog classifications")
        return 1
    print("PASS 97/97 ledger records match the pinned backlog and manual classifications")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
