#!/usr/bin/env python3
"""Compile reviewed typed effects and Tarot identity; free-text mechanics are never executed."""
import argparse
import hashlib
import json
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
HEADER = ROOT / "src/runtime/FfxHooksDll/hooks/ArcanaCatalog.generated.h"


def build():
    cards = json.loads((HERE / "cards.proposed.json").read_text())["cards"]
    definition = json.loads((HERE / "effects.v1.json").read_text())
    effects = definition["cards"]
    assert [c["id"] for c in cards] == [c["id"] for c in effects] == list(range(78))
    source = (ROOT / "src/runtime/FfxHooksDll/hooks/ArcanaCore.h").read_text()
    body = re.search(r"enum class EffectKind[^\{]*\{(.*?)\};", source, re.S).group(1)
    kinds = {v.strip() for v in body.split(",")} - {"None", "Count"}
    lines = ["// Generated by compile_catalog.py; edit effects.v1.json and the design source.",
             "#pragma once", "namespace FfxHooks::Arcana {", "inline constexpr Card kCatalog[] = {"]
    for card, row in zip(cards, effects):
        seen = set()
        assert 1 <= len(row["effects"]) <= 8
        values = []
        for effect in row["effects"]:
            kind, value = effect["kind"], effect["value"]
            assert kind in kinds and kind not in seen and type(value) is int and -100 <= value <= 500
            seen.add(kind)
            values.append("{EffectKind::" + kind + "," + str(value) + "}")
        fields = [str(card["id"]), str(card["arcana"] == "major").lower(),
                  json.dumps(card["key"]), json.dumps(card["item_name_en"]), json.dumps(card["mechanics_proposed"]),
                  json.dumps(Path(card["asset"]).name)]
        lines.append("    {" + ",".join(fields) + ",{{" + ",".join(values) + "}}},")
    identity = [{"key": c["key"], "major": c["arcana"] == "major", "id": e["id"], "effects": e["effects"]} for c, e in zip(cards, effects)]
    pack_hash = hashlib.sha256(json.dumps(identity, sort_keys=True, separators=(",", ":")).encode()).digest()
    lines += ["};", "static_assert(sizeof(kCatalog)/sizeof(kCatalog[0])==kCardCount);",
              "inline constexpr unsigned char kPackHash[32]={" + ",".join(f"0x{b:02x}" for b in pack_hash) + "};"]
    previous = definition.get("compatible_pack_hashes", [])
    stable = [{"id": c["id"], "key": c["key"], "major": c["arcana"] == "major"} for c in cards]
    if previous:
        assert hashlib.sha256(json.dumps(stable, sort_keys=True, separators=(",", ":")).encode()).hexdigest() == definition["compatible_identity_sha256"], "Cannot migrate changed card identities or weights"
    assert len(previous) == len(set(previous)) and all(re.fullmatch(r"[0-9a-f]{64}", h) for h in previous)
    assert pack_hash.hex() not in previous
    lines += ["inline constexpr unsigned char kCompatiblePackHashes[][32]={"]
    lines += ["    {" + ",".join(f"0x{b:02x}" for b in bytes.fromhex(h)) + "}," for h in previous]
    lines += ["};", "}", ""]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--write", action="store_true")
    group.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = build()
    if args.write:
        HEADER.write_text(expected)
    elif not HEADER.exists() or HEADER.read_text() != expected:
        raise SystemExit("FAIL typed Arcana catalog differs from reviewed inputs")
    print("PASS typed Arcana catalog: 78 cards, sha256=" + hashlib.sha256(expected.encode()).hexdigest())


if __name__ == "__main__":
    main()
